language: java
sudo: false
dist: xenial
jdk:
        - openjdk11
script:
        - ./gradlew shadowjar
        - ./gradlew test
        - JAR_PATH=build/libs/JavaSee-all.jar scripts/javasee init -config test.yml
        - JAR_PATH=build/libs/JavaSee-all.jar scripts/javasee test -config test.yml
